### ISSUE TITLE
ブラウザの高さが低いと死ぬ

### ISSUE THREAD

**Issue by TinyKitten** [TeamKitten/OfficialWeb#2]
![FireShot Capture 1030 - TeamKitten - teamkitten tk](https://user-images.githubusercontent.com/32848922/80324179-85beb400-886a-11ea-8552-826efc601035.png)

**Comment by makotia** [comment]
解像度高い人は一生ぼくのアイコンのあのちゃん見ることで解決するのでクローズ（しない）

**Comment by TinyKitten** [comment]
厳しい
