### ISSUE TITLE
オフライン時にメンバー一覧がロード中のまま止まる

### ISSUE THREAD

**Issue by Tosuke** [TeamKitten/OfficialWeb#20]
コンテンツはキャッシュできてもAPIの結果を永続化するのはリスクが大きいし厳しそうなのでつらそう

**Comment by TinyKitten** [comment]
[https://github.com/Akryum/vue-apollo](https://github.com/Akryum/vue-apollo)
使ってるライブラリはこれです。念のため。

**Comment by TinyKitten** [comment]
[https://dev-blog.apollodata.com/announcing-apollo-cache-persist-cb05aec16325](https://dev-blog.apollodata.com/announcing-apollo-cache-persist-cb05aec16325)
persistCacheでいけるかな

**Comment by TinyKitten** [comment]
#24 で解決したと思う　一旦Close
