### ISSUE TITLE
Nuxt化

### ISSUE THREAD

**Issue by Tosuke** [TeamKitten/OfficialWeb#33]
Pros.
- 完全に静的生成ができる
- 生成時にリクエストするのでAPI呼び出しによるオーバーヘッドをなくせる

Cons.
- メンバー情報に変更があったら再生成する必要がある
- 静的生成してる割にはサイズがデカい(よけいなモジュールを含んでいる)

試しにやってみたのは #32

**Comment by TinyKitten** [comment]
キャッシュ機構によってAPIのアクセスは軽減できるかと思います。また、定期ビルドの手間を考えるとトレードオフがあります。よって、一旦このIssueは保留とさせていただきます。

**Comment by Tosuke** [comment]
- APIアクセスの軽減以外にも初期描画の高速化などの利点があります。
- 定期ビルドはNetlifyのフックを利用すれば解決できるものと思われます。

**Comment by TinyKitten** [comment]
トレードオフはそれほどなさそうなのでReopen

**Comment by TinyKitten** [comment]
協力感謝します。マージ完了のためClose #32
